#F1 pole position predictor

Import

In [3]:
import pandas as pd

qualifying = pd.read_csv("F1(1950 - 2024) data\\raw\\qualifying.csv")
races = pd.read_csv("F1(1950 - 2024) data\\raw\\races.csv")
drivers = pd.read_csv("F1(1950 - 2024) data\\raw\\drivers.csv")
constructors = pd.read_csv("F1(1950 - 2024) data\\raw\\constructors.csv")

print('Data loaded successfully')

Data loaded successfully

Checking data

In [5]:
print(qualifying.shape)
qualifying.head()

(10494, 9)

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [6]:
qualifying.isnull().sum()

qualifyId         0
raceId            0
driverId          0
constructorId     0
number            0
position          0
q1                0
q2               22
q3               46
dtype: int64

In [12]:
races.sample(5)

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
635,636,1971,5,34,French Grand Prix,1971-07-04,\N,http://en.wikipedia.org/wiki/1971_French_Grand...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
295,296,1992,8,8,French Grand Prix,1992-07-05,\N,http://en.wikipedia.org/wiki/1992_French_Grand...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
493,494,1981,12,39,Dutch Grand Prix,1981-08-30,\N,http://en.wikipedia.org/wiki/1981_Dutch_Grand_...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
877,879,2012,20,18,Brazilian Grand Prix,2012-11-25,16:00:00,http://en.wikipedia.org/wiki/2012_Brazilian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
880,882,2013,3,17,Chinese Grand Prix,2013-04-14,07:00:00,http://en.wikipedia.org/wiki/2013_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

Data manipulation

In [ ]:
df = pd.merge(qualifying, races, how='left', on='raceId').sample(5)

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3,year,...,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
5084,5087,865,17,9,2,2,1:16.013,1:15.035,1:14.381,2012,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
6343,6366,929,1,131,44,1,1:33.928,1:32.669,1:32.571,2015,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3653,3655,350,15,205,18,18,1:25.540,\N,\N,2010,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
563,564,44,16,12,20,20,1:22.019,\N,\N,2007,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
8061,8085,1016,846,1,4,8,1:11.780,1:11.735,1:11.863,2019,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N